### ISSUE TITLE
Cannot select theme

### ISSUE THREAD

**Issue by Azn9** [Azn9/JetBrains-Discord-Integration#12]
```
2023-09-02 21:46:52,738 [   1910]   INFO - STDERR - java.lang.Error: no ComponentUI class for: javax.swing.JButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]
2023-09-02 21:46:52,740 [   1912]   INFO - STDERR - 	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:763)
2023-09-02 21:46:52,741 [   1913]   INFO - STDERR - 	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:144)
2023-09-02 21:46:52,741 [   1913]   INFO - STDERR - 	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:793)
2023-09-02 21:46:52,742 [   1914]   INFO - STDERR - 	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1078)
2023-09-02 21:46:52,742 [   1914]   INFO - STDERR - 	at java.desktop/javax.swing.JButton.updateUI(JButton.java:144)
2023-09-02 21:46:52,748 [   1920]   INFO - STDERR - 	at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2141)
2023-09-02 21:46:52,748 [   1920]   INFO - STDERR - 	at java.desktop/javax.swing.JButton.<init>(JButton.java:134)
2023-09-02 21:46:52,749 [   1921]   INFO - STDERR - 	at java.desktop/javax.swing.JButton.<init>(JButton.java:88)
2023-09-02 21:46:52,750 [   1922]   INFO - STDERR - 	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.options.types.ThemeOption.<init>(ThemeOption.kt:58)
2023-09-02 21:46:52,750 [   1922]   INFO - STDERR - 	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.options.types.ThemeOptionKt.themeChooser(ThemeOption.kt:40)
2023-09-02 21:46:52,751 [   1923]   INFO - STDERR - 	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.options.types.ThemeOptionKt.themeChooser$default(ThemeOption.kt:39)
2023-09-02 21:46:52,751 [   1923]   INFO - STDERR - 	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.impl.ApplicationSettingsImpl.<init>(ApplicationSettingsImpl.kt:140)
2023-09-02 21:46:52,752 [   1924]   INFO - STDERR - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2023-09-02 21:46:52,753 [   1925]   INFO - STDERR - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
2023-09-02 21:46:52,753 [   1925]   INFO - STDERR - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2023-09-02 21:46:52,754 [   1926]   INFO - STDERR - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
2023-09-02 21:46:52,754 [   1926]   INFO - STDERR - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
2023-09-02 21:46:52,755 [   1927]   INFO - STDERR - 	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:63)
2023-09-02 21:46:52,755 [   1927]   INFO - STDERR - 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
2023-09-02 21:46:52,756 [   1928]   INFO - STDERR - 	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
2023-09-02 21:46:52,756 [   1928]   INFO - STDERR - 	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
2023-09-02 21:46:52,757 [   1929]   INFO - STDERR - 	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
2023-09-02 21:46:52,757 [   1929]   INFO - STDERR - 	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
2023-09-02 21:46:52,758 [   1930]   INFO - STDERR - 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:94)
2023-09-02 21:46:52,758 [   1930]   INFO - STDERR - 	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:676)
2023-09-02 21:46:52,759 [   1931]   INFO - STDERR - 	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
2023-09-02 21:46:52,760 [   1932]   INFO - STDERR - 	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.ApplicationSettingsKt.getSettings(ApplicationSettings.kt:84)
2023-09-02 21:46:52,760 [   1932]   INFO - STDERR - 	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeService.load(TimeService.kt:212)
2023-09-02 21:46:52,761 [   1933]   INFO - STDERR - 	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimePreloadingActivity.preload(TimePreloadingActivity.kt:25)
2023-09-02 21:46:52,761 [   1933]   INFO - STDERR - 	at com.intellij.openapi.application.PreloadingActivity$execute$2.invoke(PreloadingActivity.kt:15)
2023-09-02 21:46:52,762 [   1934]   INFO - STDERR - 	at com.intellij.openapi.application.PreloadingActivity$execute$2.invoke(PreloadingActivity.kt:14)
2023-09-02 21:46:52,762 [   1934]   INFO - STDERR - 	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
2023-09-02 21:46:52,763 [   1935]   INFO - STDERR - 	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:199)
2023-09-02 21:46:52,764 [   1936]   INFO - STDERR - 	at com.intellij.openapi.application.PreloadingActivity.execute$suspendImpl(PreloadingActivity.kt:14)
2023-09-02 21:46:52,764 [   1936]   INFO - STDERR - 	at com.intellij.openapi.application.PreloadingActivity.execute(PreloadingActivity.kt)
2023-09-02 21:46:52,765 [   1937]   INFO - STDERR - 	at com.intellij.ide.bootstrap.AppServicePreloadingKt.executePreloadActivity(appServicePreloading.kt:167)
2023-09-02 21:46:52,765 [   1937]   INFO - STDERR - 	at com.intellij.ide.bootstrap.AppServicePreloadingKt.access$executePreloadActivity(appServicePreloading.kt:1)
2023-09-02 21:46:52,766 [   1938]   INFO - STDERR - 	at com.intellij.ide.bootstrap.AppServicePreloadingKt$postAppRegistered$4$1$1.invokeSuspend(appServicePreloading.kt:155)
2023-09-02 21:46:52,766 [   1938]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-09-02 21:46:52,767 [   1939]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-09-02 21:46:52,768 [   1940]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2023-09-02 21:46:52,768 [   1940]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2023-09-02 21:46:52,769 [   1941]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2023-09-02 21:46:52,769 [   1941]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Azn9** [comment]
This appears to be an issue only on IntelliJ, or at least, it does not happen on Rider 2023.2 🤔

**Comment by Azn9** [comment]
Cannot reproduce :(
