### ISSUE TITLE
[Bug]: Does not seem to work with Rustrover

### ISSUE THREAD

**Issue by Xyndra** [Azn9/JetBrains-Discord-Integration#121]
### What happened?

It didn't show

### IDE version

RustRover 2024.1, Build #RR-241.15989.199, built on May 18, 2024

### Plugin version

2.0.8

### What operating system are you using?

Windows

### Relevant log output

```shell
2024-06-07 19:03:52,549 [   2562] SEVERE - #c.i.o.a.i.ActionManagerImpl - ID 'DiscordActionGroup' is already taken by action 'Discord (null)' (class com.intellij.openapi.actionSystem.impl.ActionGroupStub)  (Plugin: Discord Integration). Action 'null (null)' (class com.intellij.openapi.actionSystem.impl.ActionGroupStub) cannot use the same ID (plugin dev.azn9.plugins.discord) [Plugin: dev.azn9.plugins.discord]
com.intellij.diagnostic.PluginException: ID 'DiscordActionGroup' is already taken by action 'Discord (null)' (class com.intellij.openapi.actionSystem.impl.ActionGroupStub)  (Plugin: Discord Integration). Action 'null (null)' (class com.intellij.openapi.actionSystem.impl.ActionGroupStub) cannot use the same ID (plugin dev.azn9.plugins.discord) [Plugin: dev.azn9.plugins.discord]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.reportActionIdCollision(ActionManagerImpl.kt:1995)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.registerAction(ActionManagerImpl.kt:2075)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.registerAction$default(ActionManagerImpl.kt:2061)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.registerOrReplaceActionInner(ActionManagerImpl.kt:2260)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.access$registerOrReplaceActionInner(ActionManagerImpl.kt:1)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processGroupElement(ActionManagerImpl.kt:599)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.kt:384)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.doRegisterActions(ActionManagerImpl.kt:238)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.kt:125)
	at com.jetbrains.rdserver.ui.actionPopupMenu.BackendActionManager.<init>(BackendActionManager.kt:17)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:49)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:42)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:308)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:42)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance$suspendImpl(ServiceInstanceInitializer.kt:31)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance(ServiceInstanceInitializer.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance$suspendImpl(LazyInstanceHolder.kt:83)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.instance(InstanceContainerImpl.kt:68)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:702)
	at com.intellij.platform.ide.bootstrap.ApplicationLoader$preloadNonHeadlessServices$2$5.invokeSuspend(ApplicationLoader.kt:586)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-06-07 19:03:52,674 [   2687] SEVERE - #c.i.o.a.i.ActionManagerImpl - RustRover 2024.1  Build #RR-241.15989.199
2024-06-07 19:03:52,675 [   2688] SEVERE - #c.i.o.a.i.ActionManagerImpl - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-06-07 19:03:52,675 [   2688] SEVERE - #c.i.o.a.i.ActionManagerImpl - OS: Windows 11
2024-06-07 19:03:52,676 [   2689] SEVERE - #c.i.o.a.i.ActionManagerImpl - Plugin to blame: Discord Integration V2 version: 2.0.8
2024-06-07 19:03:52,676 [   2689] SEVERE - #c.i.o.a.i.ActionManagerImpl - Last Action: 
2024-06-07 19:03:52,684 [   2697] SEVERE - #c.i.o.a.i.ActionManagerImpl - cannot create class "null" (module=PluginDescriptor(name=Discord Integration V2, id=dev.azn9.plugins.discord, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\RustRover2024.1\plugins\Discord Integration V2, version=2.0.8, package=null, isBundled=false))
com.intellij.diagnostic.PluginException: cannot create class "null" (module=PluginDescriptor(name=Discord Integration V2, id=dev.azn9.plugins.discord, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\RustRover2024.1\plugins\Discord Integration V2, version=2.0.8, package=null, isBundled=false))
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.reportActionError(ActionManagerImpl.kt:1535)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.access$reportActionError(ActionManagerImpl.kt:1)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processGroupElement(ActionManagerImpl.kt:720)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.kt:384)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.doRegisterActions(ActionManagerImpl.kt:238)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.kt:125)
	at com.jetbrains.rdserver.ui.actionPopupMenu.BackendActionManager.<init>(BackendActionManager.kt:17)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:49)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:42)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:308)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:42)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance$suspendImpl(ServiceInstanceInitializer.kt:31)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance(ServiceInstanceInitializer.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance$suspendImpl(LazyInstanceHolder.kt:83)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.instance(InstanceContainerImpl.kt:68)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:702)
	at com.intellij.platform.ide.bootstrap.ApplicationLoader$preloadNonHeadlessServices$2$5.invokeSuspend(ApplicationLoader.kt:586)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.NullPointerException
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processAddToGroupNode(ActionManagerImpl.kt:753)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processGroupElement(ActionManagerImpl.kt:690)
	... 40 more
2024-06-07 19:03:52,688 [   2701] SEVERE - #c.i.o.a.i.ActionManagerImpl - RustRover 2024.1  Build #RR-241.15989.199
2024-06-07 19:03:52,688 [   2701] SEVERE - #c.i.o.a.i.ActionManagerImpl - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-06-07 19:03:52,689 [   2702] SEVERE - #c.i.o.a.i.ActionManagerImpl - OS: Windows 11
2024-06-07 19:03:52,689 [   2702] SEVERE - #c.i.o.a.i.ActionManagerImpl - Plugin to blame: Discord Integration V2 version: 2.0.8
2024-06-07 19:03:52,689 [   2702] SEVERE - #c.i.o.a.i.ActionManagerImpl - Last Action: 
2024-06-07 19:03:52,779 [   2792]   WARN - #c.i.u.x.Binding - No accessors for com.mallowigi.idea.themes.MTThemeFacade. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
```

And also spam:

```
\JetBrainsClient\versionManagementEnabled, HKCU_64\SOFTWARE\JetBrains\JetBrainsClient\versionManagementEnabled, HKCU_32\SOFTWARE\JetBrains\JetBrainsClient\versionManagementEnabled]
2024-06-07 19:05:07,063 [  53362]   INFO - #c.i.r.OsRegistryConfigProvider - OS provided value for 'versionManagementEnabled' is not found
2024-06-07 19:05:11,875 [  58174]   INFO - Discord - Sending new presence
2024-06-07 19:05:16,889 [  63188]   INFO - Discord - Sending new presence
2024-06-07 19:05:21,905 [  68204]   INFO - Discord - Sending new presence
2024-06-07 19:05:26,917 [  73216]   INFO - Discord - Sending new presence
2024-06-07 19:05:27,335 [  73634]   INFO - #c.i.u.g.s.GistStorageImpl - Cleaning old huge-gists dirs from [C:\Users\Sammy\AppData\Local\JetBrains\RustRover2024.1\caches\huge-gists] ...
2024-06-07 19:05:27,337 [  73636]   INFO - #c.i.u.g.s.GistStorageImpl - Cleaning old huge-gists dirs finished
2024-06-07 19:05:31,921 [  78220]   INFO - Discord - Sending new presence
2024-06-07 19:05:36,935 [  83234]   INFO - Discord - Sending new presence
2024-06-07 19:05:41,963 [  88262]   INFO - Discord - Sending new presence
2024-06-07 19:05:46,964 [  93263]   INFO - Discord - Sending new presence
2024-06-07 19:05:51,967 [  98266]   INFO - Discord - Sending new presence
2024-06-07 19:05:56,981 [ 103280]   INFO - Discord - Sending new presence
2024-06-07 19:06:01,987 [ 108286]   INFO - Discord - Sending new presence
2024-06-07 19:06:06,996 [ 113295]   INFO - Discord - Sending new presence
2024-06-07 19:06:12,005 [ 118304]   INFO - Discord - Sending new presence
2024-06-07 19:06:17,006 [ 123305]   INFO - Discord - Sending new presence
2024-06-07 19:06:22,010 [ 128309]   INFO - Discord - Sending new presence
2024-06-07 19:06:27,021 [ 133320]   INFO - Discord - Sending new presence
2024-06-07 19:06:32,030 [ 138329]   INFO - Discord - Sending new presence
2024-06-07 19:06:35,206 [ 141505]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-06-07 19:06:35,207 [ 141506]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-06-07 19:06:37,036 [ 143335]   INFO - Discord - Sending new presence
2024-06-07 19:06:42,040 [ 148339]   INFO - Discord - Sending new presence
2024-06-07 19:06:47,042 [ 153341]   INFO - Discord - Sending new presence
2024-06-07 19:06:52,055 [ 158354]   INFO - Discord - Sending new presence
2024-06-07 19:06:57,062 [ 163361]   INFO - Discord - Sending new presence
2024-06-07 19:07:02,071 [ 168370]   INFO - Discord - Sending new presence
2024-06-07 19:07:07,074 [ 173373]   INFO - Discord - Sending new presence
2024-06-07 19:07:12,075 [ 178374]   INFO - Discord - Sending new presence
2024-06-07 19:07:17,085 [ 183384]   INFO - Discord - Sending new presence
2024-06-07 19:07:22,090 [ 188389]   INFO - Discord - Sending new presence
2024-06-07 19:07:23,058 [ 189357]   WARN - #c.i.i.a.CopyTBXReferenceAction - Cannot find TBX tool for IDE: RustRover
2024-06-07 19:07:27,095 [ 193394]   INFO - Discord - Sending new presence
2024-06-07 19:07:32,021 [ 198320]   WARN - #c.i.i.a.CopyTBXReferenceAction - Cannot find TBX tool for IDE: RustRover
2024-06-07 19:07:32,098 [ 198397]   INFO - Discord - Sending new presence
2024-06-07 19:07:37,101 [ 203400]   INFO - Discord - Sending new presence
2024-06-07 19:07:42,109 [ 208408]   INFO - Discord - Sending new presence
2024-06-07 19:07:47,120 [ 213419]   INFO - Discord - Sending new presence
2024-06-07 19:07:52,122 [ 218421]   INFO - Discord - Sending new presence
2024-06-07 19:07:57,124 [ 223423]   INFO - Discord - Sending new presence
2024-06-07 19:08:02,132 [ 228431]   INFO - Discord - Sending new presence
2024-06-07 19:08:07,134 [ 233433]   INFO - Discord - Sending new presence
2024-06-07 19:08:07,659 [ 233958]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-06-07 19:08:07,660 [ 233959]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-06-07 19:08:07,709 [ 234008]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=StableUI, containerState=COMPONENT_CREATED, componentStore=D:\Code\Rust\StableUI)RunManager took 37 ms
2024-06-07 19:08:12,139 [ 238438]   INFO - Discord - Sending new presence
2024-06-07 19:08:17,150 [ 243449]   INFO - Discord - Sending new presence
2024-06-07 19:08:22,164 [ 248463]   INFO - Discord - Sending new presence
2024-06-07 19:08:27,170 [ 253469]   INFO - Discord - Sending new presence
2024-06-07 19:08:32,171 [ 258470]   INFO - Discord - Sending new presence
2024-06-07 19:08:37,177 [ 263476]   INFO - Discord - Sending new presence
2024-06-07 19:08:42,179 [ 268478]   INFO - Discord - Sending new presence
2024-06-07 19:08:47,178 [ 273477]   INFO - Discord - Sending new presence
2024-06-07 19:08:52,192 [ 278491]   INFO - Discord - Sending new presence
2024-06-07 19:08:57,199 [ 283498]   INFO - Discord - Sending new presence
2024-06-07 19:09:02,213 [ 288512]   INFO - Discord - Sending new presence
2024-06-07 19:09:07,214 [ 293513]   INFO - Discord - Sending new presence
2024-06-07 19:09:12,228 [ 298527]   INFO - Discord - Sending new presence
2024-06-07 19:09:17,241 [ 303540]   INFO - Discord - Sending new presence
2024-06-07 19:09:22,253 [ 308552]   INFO - Discord - Sending new presence
2024-06-07 19:09:27,266 [ 313565]   INFO - Discord - Sending new presence
2024-06-07 19:09:32,269 [ 318568]   INFO - Discord - Sending new presence
2024-06-07 19:09:36,872 [ 323171]   INFO - #c.i.j.n.n.WorkingDirectoryDependentNpmPackageVersionManager - Version fetched successfully: 10.0.0; command: "C:\Program Files\nodejs\npm.cmd" --version, duration: 1011ms
2024-06-07 19:09:37,281 [ 323580]   INFO - Discord - Sending new presence
2024-06-07 19:09:42,285 [ 328584]   INFO - Discord - Sending new presence
2024-06-07 19:09:47,298 [ 333597]   INFO - Discord - Sending new presence
2024-06-07 19:09:52,311 [ 338610]   INFO - Discord - Sending new presence
2024-06-07 19:09:57,321 [ 343620]   INFO - Discord - Sending new presence
2024-06-07 19:10:02,324 [ 348623]   INFO - Discord - Sending new presence
2024-06-07 19:10:07,328 [ 353627]   INFO - Discord - Sending new presence
2024-06-07 19:10:12,330 [ 358629]   INFO - Discord - Sending new presence
2024-06-07 19:10:17,342 [ 363641]   INFO - Discord - Sending new presence
2024-06-07 19:10:22,354 [ 368653]   INFO - Discord - Sending new presence
2024-06-07 19:10:27,358 [ 373657]   INFO - Discord - Sending new presence
2024-06-07 19:10:32,371 [ 378670]   INFO - Discord - Sending new presence
2024-06-07 19:10:37,382 [ 383681]   INFO - Discord - Sending new presence
2024-06-07 19:10:42,387 [ 388686]   INFO - Discord - Sending new presence
2024-06-07 19:10:47,394 [ 393693]   INFO - Discord - Sending new presence
2024-06-07 19:10:52,395 [ 398694]   INFO - Discord - Sending new presence
2024-06-07 19:10:57,410 [ 403709]   INFO - Discord - Sending new presence
2024-06-07 19:11:02,411 [ 408710]   INFO - Discord - Sending new presence
2024-06-07 19:11:07,425 [ 413724]   INFO - Discord - Sending new presence
2024-06-07 19:11:12,429 [ 418728]   INFO - Discord - Sending new presence
2024-06-07 19:11:17,440 [ 423739]   INFO - Discord - Sending new presence
2024-06-07 19:11:22,439 [ 428738]   INFO - Discord - Sending new presence
2024-06-07 19:11:27,445 [ 433744]   INFO - Discord - Sending new presence
2024-06-07 19:11:28,104 [ 434403]   WARN - #c.i.i.a.CopyTBXReferenceAction - Cannot find TBX tool for IDE: RustRover
2024-06-07 19:11:32,576 [ 438875]   INFO - Discord - Sending new presence
```

**Comment by Azn9** [comment]
Please make sure you uninstalled all old versions of the plugin (either Alpaca's ones or versions prior 2.0.8)

**Comment by Xyndra** [comment]
![image](https://github.com/Azn9/JetBrains-Discord-Integration/assets/71836523/e0c6cfa4-cfe0-4f8e-809c-08fc1a47fc2d)

**Comment by Azn9** [comment]
Can you send me your whole idea.log file on discord please?

**Comment by Xyndra** [comment]
ok I did

**Comment by Xyndra** [comment]
My discord is weird it seems to be visible just not for me
