### ISSUE TITLE
cannot execute preloading activity com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimePreloadingActivity

### ISSUE THREAD

**Issue by Matyu9** [Azn9/JetBrains-Discord-Integration#26]
When I start **Pycharm Pro 2023.3 EAP**, I have this error:

```
com.intellij.diagnostic.PluginException: cannot execute preloading activity com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimePreloadingActivity [Plugin: com.almightyalpaca.intellij.plugins.discord]
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt.executePreloadActivity(appServicePreloading.kt:208)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt.access$executePreloadActivity(appServicePreloading.kt:1)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt$postAppRegistered$4$1.invokeSuspend(appServicePreloading.kt:189)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeService (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Discord Integration V2, id=com.almightyalpaca.intellij.plugins.discord, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharm2023.3/JetBrains-Discord-Integration, version=2.0.3, package=null, isBundled=false), packagePrefix=null, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1379)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1355)
	at com.intellij.serviceContainer.LightServiceComponentAdapter.doCreateInstance(lightService.kt:30)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:176)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:155)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:97)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:1050)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:966)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeServiceKt.getTimeService(TimeService.kt:249)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimePreloadingActivity.preload(TimePreloadingActivity.kt:26)
	at com.intellij.openapi.application.PreloadingActivity$execute$2.invoke(PreloadingActivity.kt:15)
	at com.intellij.openapi.application.PreloadingActivity$execute$2.invoke(PreloadingActivity.kt:14)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:329)
	at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:206)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:205)
	at com.intellij.openapi.application.PreloadingActivity.execute$suspendImpl(PreloadingActivity.kt:14)
	at com.intellij.openapi.application.PreloadingActivity.execute(PreloadingActivity.kt)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt.executePreloadActivity(appServicePreloading.kt:201)
	... 8 more
Caused by: java.lang.AssertionError: Thread[DefaultDispatcher-worker-68,5,main]
	at com.intellij.ide.IdeEventQueue.<init>(IdeEventQueue.kt:140)
	at com.intellij.ide.IdeEventQueue.<init>(IdeEventQueue.kt)
	at com.intellij.ide.IdeEventQueue$Companion$_instance$2.invoke(IdeEventQueue.kt:160)
	at com.intellij.ide.IdeEventQueue$Companion$_instance$2.invoke(IdeEventQueue.kt:160)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.ide.IdeEventQueue$Companion.get_instance(IdeEventQueue.kt:160)
	at com.intellij.ide.IdeEventQueue$Companion.getInstance(IdeEventQueue.kt:163)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeService.<init>(TimeService.kt:195)
	at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(ComponentManagerImpl.kt:1361)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1370)
	... 30 more

```

Here is my Discord Version:
```
Stable 236850 (4025e11) 
Host 0.0.31 x64 
Linux 64-Bit (6.5.5-Zen1-1-Zen)
```

Respectfully

**Comment by Azn9** [comment]
Cannot reproduce on windows, I'll try to fix it but it is most likely related to #20

**Comment by HTGAzureX1212** [comment]
@Azn9 I just reproduced it on Windows, with the same backtrace as OP.

Please find below:
### IDE Version
```
RustRover 2023.3 EAP
Build #RR-233.8264.22, built on October 11, 2023
Licensed to RustRover EAP user: <redactd>
Expiration date: December 10, 2023
Runtime version: 17.0.8.1+7-b1063.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4078M
Cores: 16
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.nasller.CodeGlancePro (1.7.6)
  com.almightyalpaca.intellij.plugins.discord (2.0.3)
  zielu.gittoolbox (500.0.21+222)
```
### Discord Version
```
Canary 239360 (427cfe2)
Host 1.0.82 x86 (38800)
Windows 10 64-Bit (10.0.22635)
```
### OS Version
```
Windows 11 Home 23H2 (22635.2486)
```

**Comment by Azn9** [comment]
Thanks for the report @HTGAzureX1212! I sent on [discord](https://discord.gg/mEDvg6sYp2) a beta version, if you want to test it to see if it resolves the issue for you ;)

**Comment by HTGAzureX1212** [comment]
@Azn9 The issue is resolved after applying the updated beta build. Thanks a lot! 👍
