### ISSUE TITLE
[Deprecation]: ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by maxoux53** [Azn9/JetBrains-Discord-Integration#79]
### What happened?

J'ai pas constaté de problèmes (rien de visible en tout cas) mais ce message d'erreur est apparu
![image](https://github.com/Azn9/JetBrains-Discord-Integration/assets/71935156/7a87bb50-5bb3-463e-afa5-78b0c693303b)

### IDE version

CLion 2024.1 EAP (Nova) Build #CL-241.11109, built on January 31, 2024

### Plugin version

2.0.8

### What operating system are you using?

MacOS

### Relevant log output

```shell
com.intellij.diagnostic.PluginException: ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon. 'dev.azn9.plugins.discord.actions.ApplicationShowAction' must override getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: dev.azn9.plugins.discord]
    at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
    at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
    at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
    at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
    at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:198)
```

**Comment by WarningImHack3r** [comment]
@Azn9 si jamais tu as besoin de tips, j'ai fix le même problème pour mon plugin : https://github.com/WarningImHack3r/npm-update-dependencies/pull/80, c'est super simple à fix

**Comment by Azn9** [comment]
Merci @WarningImHack3r ! Là mon plus gros problème c'est de trouver du temps pour travailler dessus 😅

**Comment by WarningImHack3r** [comment]
Je te prépare une petite PR dans la journée ;)
