### ISSUE TITLE
[Bug]: Not showing up in discord canary

### ISSUE THREAD

**Issue by GamerBossHarmon** [Azn9/JetBrains-Discord-Integration#90]
### What happened?

The plugin only seems to work about 25% of the time; any other time, it does not and shows this.

![Nevers loads](https://github.com/Azn9/JetBrains-Discord-Integration/assets/93500405/d9677164-0b11-4efb-9c31-a1f547caf788)

Is there a way to see the console output so that I can look for a more direct error?

### IDE version

2023.3.3

### Plugin version

2.0.8

### What operating system are you using?

Windows

**Comment by Azn9** [comment]
Can you send me your logs file via Discord, you can DM me `@azn9` or via email at contact@azn9.dev.
You can get them via the "Help" menu > "Show log in explorer" then send the "idea.log" file.

**Comment by GamerBossHarmon** [comment]
Ok, I have sent the log file to you over on discord, after look in the log file a bit it seem to me that it might be related to this

```2024-03-10 20:38:57,411 [  14513]   INFO - Discord - Sending new presence
2024-03-10 20:38:57,412 [  14514]   WARN - Discord - Error connecting to ipc
dev.cbyrne.kdiscordipc.core.error.ConnectionError$NoIPCFile: Failed to find an IPC file. Is Discord open? Is this application allowed to access temporary files?
	at dev.cbyrne.kdiscordipc.core.error.ConnectionError$NoIPCFile.<clinit>(ConnectionError.kt)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:131)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:135)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:135)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:135)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:135)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:135)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:135)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:135)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:135)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:135)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:135)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.connect(SocketHandler.kt:89)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect(KDiscordIPC.kt:87)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect$default(KDiscordIPC.kt:80)
	at dev.azn9.plugins.discord.rpc.connection.DiscordIpcConnection$connect$2$1.invokeSuspend(DiscordIpcConnection.kt:66)
	at dev.azn9.plugins.discord.rpc.connection.DiscordIpcConnection$connect$2$1.invoke(DiscordIpcConnection.kt)
	at dev.azn9.plugins.discord.rpc.connection.DiscordIpcConnection$connect$2$1.invoke(DiscordIpcConnection.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:89)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:151)
	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:107)
	at dev.azn9.plugins.discord.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:65)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)```

**Comment by Azn9** [comment]
Do you run your Discord as admin?

**Comment by Azn9** [comment]
(We talked about it in PM)
It appears that the plugin "Discord Volume Mixer" by Danol for StreamDeck overrides the IPC connection and prevent access to it. I've not found anything relevant in their source code, and I cannot detect this and prevent it on my end. I'd suggest opening an issue on their repo instead.
